services:
  client:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/src
      - client-node-modules:/src/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  server:
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/src
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./server/.env

  nginx:
    build: ./nginx
    ports:
      - "1935:1935" # RTMP
      - "8080:8080" # HTTP HLS
    volumes:
      - hls-data:/mnt/hls

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./server/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  client-node-modules:
  hls-data:
  postgres-data:
