services:
  client:
    build: ./client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/src
      - client_node_modules:/src/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

  server:
    build: ./server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/src
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./server/.env

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./server/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - ./server/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  client_node_modules:
  postgres-data:
